query ($nextCursor: String) {
  projects(first: 48, after: $nextCursor, state: LIVE, sort: NEWEST) {
    edges {
      node {
        id
        name
        slug
        url
        percentFunded
        category {
          name
        }
        pledged {
          amount
          currency
        }
        goal {
          amount
        }
        description
        backersCount
        launchedAt
        deadlineAt
        isLaunched
        isProjectOfTheDay
        isProjectWeLove

        creator {
          name
          url
          launchedProjects {
            totalCount
          }
        }

        collaborators {
          edges {
            node {
              name
            }
          }
        }
      }
    }

    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
