query ($nextCursor: String) {
  projects(first: 10, after: $nextCursor, state: LIVE, sort: NEWEST) {
    edges {
      node {
        id
        name
        url
        percentFunded
        pledged {
          amount
          currency
        }
        description
        creator {
          name
          url
        }
        isLaunched
        launchedAt
        backersCount
        deadlineAt
        isProjectOfTheDay
        isProjectWeLove
      }
      cursor
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
