query ($nextCursor: String) {
  projects(recommended: true, first: 50, after: $nextCursor, state: LIVE) {
    edges {
      node {
        id
        name
        url
        percentFunded
        pledged {
          amount
          currency
        }
        description
        creator {
          name
          url
        }
        isLaunched
        backersCount
        deadlineAt
        isProjectOfTheDay
        isProjectWeLove
      }
      cursor
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
