query ($slug: String!) {
  project(slug: $slug) {
    id
    creator {
      name
      launchedProjects {
        totalCount
      }
    }
    collaborators {
      edges {
        node {
          name
        }
      }
    }
  }
}
